### ISSUE TITLE
CRC for smarthome:ebus send (...)

### ISSUE THREAD

**Issue by Rolli1962** [csowada/openhab2-addons#6]
extend test CMD on ebus automatically with necessary CRC (e.g. as option).
If could also be implement show the complete telegram with answer of device on console.

As exmple on karaf console will be entered:
smarthome:ebus send "FF ED 07 04 00"
On the ebus will be send out
"FF ED 07 04 00 CC"
As result will be presented
"FF";"ED";"07 04";"00 CC 00 0A B5 56 4D 53 30 32 01 08 17 03 53 00"

**Comment by csowada** [comment]
Fixed in https://github.com/csowada/openhab2-addons/commit/8e085437b32e3b1a48d02bd12c086ab0afeca46e
