### ISSUE TITLE
boiler.control.setopdata not shown in things

### ISSUE THREAD

**Issue by Rolli1962** [csowada/openhab2-addons#8]
The values of boiler.control.setopdata are not listed in device BAI (Openhab ->Configurations->Things).
It was present some versions ago, think in 2.4.0-RC7b was OK. As least I had mapped one value.

My investigating gave the meaning, it should be present. But somewhat is unhappy ...

The log after restart of openhab present:
2020-02-06 08:34:08.946 [WARN ] [internal.things.EBusTypeProviderImpl] - eBUS command boiler.control.setopdata only contains a setter channel!
2020-02-06 08:34:12.596 [INFO ] [ing.ebus.internal.EBusHandlerFactory] - Use eBUS binding 2.5.1.202001291838 [eBUS core: 1.0.5.202001291834, eBUS configuration: 1.0.5.202001291835]
2020-02-06 08:34:12.723 [INFO ] [ing.ebus.internal.EBusHandlerFactory] - eBUS core -> timestamp 202001291834, commit: #3d1c915, build-no: #null
2020-02-06 08:34:12.799 [INFO ] [ing.ebus.internal.EBusHandlerFactory] - eBUS configuration -> timestamp 202001291835, commit: #3f20d94, build-no: #null

The telegram example show it is mapped correctly:
2020-02-05 13:57:40;"10";"08";"B5 10";"09 00 00 77 FF FF FF 00 00 00 D4 00 01 01 9A 00";SET > bai.boiler.control.setopdata

And the configuration part of vaillant-bai00-configuration.json  seems also be OK:
        {
            "label":    "Operational Data from Room Controller to Burner Control Unit",
            "id":       "boiler.control.setopdata",
            "command":  "B5 10",
            "set": {
                "master": [
                    {"type": "static", "default": "00 00"},
                    {"name": "temp_d_lead_water", "type": "data1c", "label": "Lead water target temperature", "min": 0, "max": 100, "format":"%.1f°C"},
                    {"name": "temp_d_srv_water", "type": "data1c", "label": "Service water target temperature", "min": 0, "max": 100, "format":"%.1f°C"},
                    {"type": "static", "default": "FF FF"},
                    {"type": "byte", "children": [
                        {"name": "turnoff_water_heating", "type": "bit", "label": "Turn off water heating"},
                        {"type": "bit"},
                        {"name": "turnoffservice_water_heating", "type": "bit", "label": "Turn off service water heating"},
                        {"type": "bit"},
                        {"type": "bit"},
                        {"type": "bit"},
                        {"type": "bit"},
                        {"type": "bit"}
                        ]},
                    {"type": "static", "default": "00 00"}
                ],
                "slave": [
                    {"type": "static", "default": "01"}
                ]
            }
        },

**Comment by csowada** [comment]
Yes, it is simply filtered out. This is the reason for the message `` eBUS command boiler.control.setopdata only contains a setter channel!`` in the log. I'll include it in the next release. But maybe the new Rule Action feature is better to control the exact telegram content.

**Comment by csowada** [comment]
Included in binding version 2.5.1-6
